name: Publish NuGet Package

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Publish NuGet Package

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Increment package version
        id: version
        run: |
          VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" ./<project-path>/<project-name>.csproj)
          # Разбиваем на major.minor.patch
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "New version: $NEW_VERSION"
          sed -i "s/<Version>$VERSION<\/Version>/<Version>$NEW_VERSION<\/Version>/" ./<project-path>/<project-name>.csproj
          echo "version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Build and pack
        run: dotnet pack ./<project-path>/<project-name>.csproj -c Release -o ./out

      - name: Publish package to NuGet
        run: dotnet nuget push ./out/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
